### ISSUE TITLE
License

### ISSUE THREAD

**Issue by svaksha** [triketora/women-in-software-eng#218]
Hi,
I could not find any license information - how is this repository licensed? Please include this information in the repo.
Thanks,
s

**Comment by janl** [comment]
Heya, I’m also intersted in the license of this work. I’d be interested in forking & translating this to collect similar data in other countries.

**Comment by janl** [comment]
Sorry to post again: I’m also happy to recommend suitable licenses and explain the whys and the hows, if this helps any.

**Comment by triketora** [comment]
@janl Would love to hear your recommendations on licenses!

**Comment by svaksha** [comment]
@triketora, did you close this because you were unable to decide on the license? 

Here are some helpful links: 
* https://help.github.com/articles/adding-a-license-to-a-repository/
* https://choosealicense.com/ has some suggestions 
* This [discussion](https://github.com/github/choosealicense.com/issues/196#issuecomment-42115447) on repos without the license is an interesting read for developers and those who fork and/or contribute to repos without a license.

HTH.

**Comment by svaksha** [comment]
Also wanted to add that besides the code, you also have data in the repo, disjunct from code, so here is another link with 3 licenses to choose from: https://opendatacommons.org/licenses/
