### ISSUE TITLE
Voluntary response bias? 

### ISSUE THREAD

**Issue by imshivs** [triketora/women-in-software-eng#265]
Hey folks, I love everything about this initiative. I'm concerned, however, that the approach is going to give us some skewed and/or inaccurate data. I'm sure others have considered this and just wanted to open up a forum for discussion. How do we tackle companies uncomfortable or embarrassed with their numbers and build a better picture of diversity (or lack thereof) in software engineering?

**Comment by triketora** [comment]
Yep, there is definitely ample selection bias (but of course the benefits are still strong for having granular information publicly available). One possibility is to set up another data repository that anonymizes the data that companies submit, which can compute benchmarks over all the data and release aggregated information, as well as let companies know how they compare to others, e.g. percentile ranking, and they can choose to make that information public or not.
