### ISSUE TITLE
Countries

### ISSUE THREAD

**Issue by birgitta410** [triketora/women-in-software-eng#298]
It's also really hard to find this type of data in other countries, e.g. in my home country, Germany. I can only guess that most of these companies are based in the US - ?

Any plans to add a "country" field, or multiple data files for different countries? Or maybe I'll create a fork... Any forks yet for other countries?

**Comment by triketora** [comment]
Yes, most of these companies are US-based, although some also employ people in other countries. One of the difficulties with splitting the data by country is in defining what that means -- does a multinational company submit its data per country? Or do we use the country field to demarcate where the company is headquartered, and still count all its employees together? 

If you want to create a fork that handles international data that'd be awesome!
