### ISSUE TITLE
Let's make this more than binary

### ISSUE THREAD

**Issue by lsblakk** [triketora/women-in-software-eng#3]
I'd like this amazing idea to benefit from more than just women:men identities - let's broaden and allow for people to self-id in other categories then analyze the data accordingly.

eg: instead of pulling num_female_eng and num_eng let's say grab num\* and chart that so a company could have (and people could make pull requests for data that looks like):

[company_name]
        company: Name
        num_women_eng: 13
        num_men_eng: 92
        num_transwoman_eng: 2
        num_genderqueer_eng: 1
        last_updated: 10/20/2013

Then sort this based on whatever is between num_  and _eng to get the columns or whatever. 

I could submit a patch for this probably but putting it in an issue in case anyone else wants to tackle this before I get to it.  Thanks for doing this!

**Comment by mLuby** [comment]
Could introduce a small change of modifying the data by +1/-1 here to add plausible deniability. Makes the data less accurate, but protects people who might not be out. Might spark some interesting discussions. :)

**Comment by suisea** [comment]
as a trans person i think delineating transness is actually kind of othering of trans people in this case? trans women are women.

however i do strongly desire at least a third category for all nonbinary genders. women/nonbinary/male is easy enough, isn't it? it bothers me that the data visualisation for /this data assumes binary genders are the only ones that exist.

**Comment by kivikakk** [comment]
:+1: for non-binary data (while not separating trans stats out).
